DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'REGION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'LION';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'POND';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'AMBULANCEAREA';

DROP TABLE LION;
DROP TABLE REGION;
DROP TABLE POND;
DROP TABLE AMBULANCEAREA;

